### ISSUE TITLE
PDOException Table 'livechat-db.lhc_twilio_phone' doesn't exist

### ISSUE THREAD

**Issue by gabehou** [LiveHelperChat/twilio#2]
Fresh Install of LHC

1. Add twilio to extension directory
2. Edit twillio settings file 
3. Enable twillio by adding to the settings file. 
4. LHC admin Modules -> Twilio -> Twilio Phones 
-  PDOException Object
(
    [message:protected] => SQLSTATE[42S02]: Base table or view not found: 1146 Table 'liveichat-db.lhc_twilio_phone' doesn't exist
    [string:Exception:private] => 
    [code:protected] => 42S02
    [file:protected] => /home/chatexphvac/public_html/lib/core/lhcore/lhdbtrait.php
    [line:protected] => 219
    [trace:Exception:private] => Array
        (
            [0] => Array
                (
                    [file] => /lib/core/lhcore/lhdbtrait.php
                    [line] => 219
                    [function] => execute
                    [class] => PDOStatement
                    [type] => ->
                    [args] => Array
                        (
                        )

                )

            [1] => Array
                (
                    [file] => /extension/twilio/modules/lhtwilio/list.php
                    [line] => 16
                    [function] => getCount
                    [class] => erLhcoreClassModelTwilioPhone
                    [type] => ::
                    [args] => Array
                        (
                            [0] => Array
                                (
                                )

                        )

                )

            [2] => Array
                (
                    [file] => /lib/core/lhcore/lhmodule.php
                    [line] => 98
                    [args] => Array
                        (
                            [0] => extension/twilio/modules/lhtwilio/list.php
                        )

                    [function] => include
                )

            [3] => Array
                (
                    [file] => /lib/core/lhcore/lhmodule.php
                    [line] => 486
                    [function] => runModule
                    [class] => erLhcoreClassModule
                    [type] => ::
                    [args] => Array
                        (
                        )

                )

            [4] => Array
                (
                    [file] => index.php
                    [line] => 39
                    [function] => moduleInit
                    [class] => erLhcoreClassModule
                    [type] => ::
                    [args] => Array
                        (
                        )

                )

        )

    [previous:Exception:private] => 
    [errorInfo] => Array
        (
            [0] => 42S02
            [1] => 1146
            [2] => Table 'livechat-db.lhc_twilio_phone' doesn't exist
        )

)

**Comment by remdex** [comment]
Hi,

You have to execute
`php cron.php -s site_admin -e twilio -c cron/update_structure`

Or
```
CREATE TABLE `lhc_twilio_chat` (  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT, `chat_id` bigint(20) unsigned NOT NULL, `phone` varchar(15) NOT NULL, `ctime` int(11) NOT NULL, `utime` int(11) NOT NULL, PRIMARY KEY (`id`),  KEY `phone_utime` (`phone`,`utime`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `lhc_twilio_phone` (  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT, `phone` varchar(15) NOT NULL,`originator` varchar(15) NOT NULL, `account_sid` varchar(35), `auth_token` varchar(35), `dep_id` int(11) unsigned NOT NULL, `chat_timeout` int(11) unsigned NOT NULL, PRIMARY KEY (`id`), KEY `phone` (`phone`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```
